local_sources:
  - name: local_webcams
    webcams:
    - webcam_name: local_webcaml_1
      webcam_number: 0
      enable: true
    - webcam_name: local_webcaml_1
      webcam_number: 1
      enable: false
  - name: local_video_files
    video_files:
    - video_name: video01
      location: 'c:\\...'
      enable: false
    - video_name: video02
      location: 'c:\\...'
      enable: false

network_sources:
  - name: network_webcams
    webcams:
    - webcam_name: webcamr0
      webcam_ip: x.x.x.x
      enable: false
    - webcam_name: webcamr1
      webcam_ip: y.y.y.y
      enable: false
