general:
  - data_dir:   '/home/vito/dev/fr-w-sface/data'
  - log_dir:    '/home/vito/dev/fr-w-sface/log'
  - output_dir: '/home/vito/dev/fr-w-sface/out'

local_sources:
  - name: local_webcams
    webcams:
    - webcam_name: local_webcaml_1
      webcam_number: 0
      enabled: True
    - webcam_name: local_webcaml_1
      webcam_number: 1
      enabled: True
  - name: local_video_files
    video_files:
    - video_name: video01
      location: '/home/vito/r/videocamara/1682921183173.mp4'
      enabled: True
      fragment_duration: 60
      fps: 14
    - video_name: video02
      location: '/home/vito/r/videocamara/1692455074607.mp4'
      enabled: False
      fragment_duration: 60
      fps: 14

network_sources:
  - name: network_webcams
    webcams:
    - webcam_name: webcamr0
      webcam_ip: x.x.x.x
      enabled: 'false'
    - webcam_name: webcamr1
      webcam_ip: y.y.y.y
      enabled: 'false'
